#!/bin/bash

## Get values

## Network
locip=$(hostname -I | cut -d' ' -f1)
wanip=$(dig @resolver4.opendns.com myip.opendns.com +short)
wgip=$(ip -f inet addr show wg0 | sed -En -e 's/.*inet ([0-9.]+).*/\1/p')
lhname=$(hostname)
whname=$(nslookup $wanip | grep  "name =" | awk '{print $4}' | sed 's/.$//')

## Raspberry Pi
rpimodel=$(tr -d '\0' < /proc/device-tree/model)
cputemp=$(vcgencmd measure_temp  | sed s/"temp="// | sed s/"'C"//)
cpumodel=$(lscpu | grep 'Model name:' | sed 's/Model name://' | awk '{$1=$1;print}')
cpuspeed=$(vcgencmd get_config arm_freq | sed s/"arm_freq="//)

## Memory
totmem=$(cat /proc/meminfo | grep "MemTotal" | sed 's/MemTotal://' | sed 's/kB//' | awk '{$1=$1;print}' | awk '{print $1/(1024)}' | awk '{printf "%d\n", int($0)}')
availablemem=$(cat /proc/meminfo | grep "MemAvailable" | sed 's/MemAvailable://' | sed 's/kB//' | awk '{$1=$1;print}' | awk '{print $1/(1024)}' | awk '{printf "%d\n", int($0)}')

## Disk
rootpart=$(df | grep /dev/root | awk '{print $2}' | awk '{print $1/1024}')
bootpart=$(df | grep /boot | awk '{print $2}' | awk '{print $1/1024}')
disktotal=$(calc $bootpart + $rootpart)
rootavailable=$(df | grep /dev/root | awk '{print $4}' | awk '{print $1/1024}')
bootavailable=$(df | grep /boot | awk '{print $4}' | awk '{print $1/1024}')
available=$(calc $rootavailable+$bootavailable)

## Statistics


## Display values
echo ""
echo "Network"
echo "-------"
echo "Local IP          = $locip"
echo "WAN IP            = $wanip"
echo "WireGuard IP      = $wgip"
echo "Local Hostname    = $lhname"
echo "WAN Hostname      = $whname"
echo ""
echo "Raspberry Pi"
echo "------------"
echo "Raspberry Pi      = $rpimodel"
echo "temperature       = $cputemp"
echo "CPU Model         = $cpumodel"
echo "CPU Speed (MHz)   = $cpuspeed"
echo ""
echo "Memory"
echo "----------"
echo "Total Memory (MB) = $totmem"
echo "Free Memory (MB)  = $availablemem"
echo ""
echo "SD Card"
echo "-------"
echo "Total     /boot/ (MB)     = $bootpart"
echo "Total     /dev/root/ (MB) = $rootpart"
echo "Free /boot/ (MB)          = $bootavailable"
echo "Free /dev/root/ (MB)      = $rootavailable"
echo ""
echo "Statistics"
echo "----------"
echo "Load Average      ="
echo "Running Pocesses  ="
echo ""
